###
post http://localhost:4000/auth/register
content-type: application/json

{
    "name": "rezal",
    "email": "rezall@gmail.com",
    "password": "rezal123"
}

###
post http://localhost:4000/auth/login
content-type: application/json

{
    "email": "rezal@gmail.com",
    "password": "rezal123"
}

###
post http://localhost:4000/users
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYjRiNjQwLWM5MjgtNDBiNy1hYjk1LTk2MGE0ZGQwMmY1ZCIsImlhdCI6MTcxNzMzNzg4NywiZXhwIjoxNzE3MzQxNDg3fQ.UwVTG5wzHBH8MMDoVHbNZuUNp9HFuPeOhyASC8rM-B4

{
    "username":"rezalllllll",
    "email":"rezal@gmail.com",
    "job":"Petani",
    "phone_number":"082883774884",
}

# search
###
get http://localhost:4000/artikel/search?q=harga
content-type: application/json


###
get http://localhost:7000/spaces
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzNmE4M2NjLWVjNjctNDEzYy1iNmVlLWM0YTE5MWUxZTQ3ZSIsImlhdCI6MTcxNzI5NDMyMSwiZXhwIjoxNzE3Mjk3OTIxfQ.88ht9gNKbKRCsG9c38hlFDCfnCNG_cNo8ForxWj-To0

{
    "title": "Bagaimana cara membuat pupuk",
    "description": "berikan saya contoh"
}